repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^gym/
      - id: end-of-file-fixer
        exclude: ^gym/
      - id: check-yaml
        exclude: ^gym/
      - id: check-added-large-files
        exclude: ^gym/
      - id: check-merge-conflict
        exclude: ^gym/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^gym/
      - id: ruff-format
        exclude: ^gym/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        exclude: ^gym/
        verbose: true
        args: [--show-error-codes]
        # Allow mypy to fail without blocking the commit
        # It will still show errors but won't prevent committing
        stages: [manual]
